include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    only_throw_errors: ignore
    unused_shown_name: ignore
linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: false