name: customizable_dropdown_button
description: "Drop Down Button With Choose menu position"
version: 1.0.0
homepage: https://github.com/DemienIlnutskiy/flutter_custom_drop_down_button

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
